version: "3"

services:
    mybash:
      image: myapp:v1.2
      env_file:
        - configs/${RUNTIME:-staging}.env
      build:
        context: .
      volumes:
          - ./local/:/volumes/
      ports:
        - ${HTTP_PORT:-8080}:8080


