apiVersion: v1
kind: Pod
metadata:
  name: pod-daniela
  labels:
    role: myrole
  namespace: wize-1
# specification
spec:
  containers:
    - name: webserver
      image: httpd:alpine
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
      resources: {}
    - name: db
      image: mysql
      ports:
        - name: mysql
          containerPort: 3306
          protocol: TCP
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: mypassword
      resources: {}
    - name: whoami
      image: jwilder/whoami
      ports:
        - name: whoami
          containerPort: 8000
          protocol: TCP
      resources: {}
