apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: frontend
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://2986C3C9E42B6F9F1449C0338F8C865D.gr7.us-east-2.eks.amazonaws.com
  project: default
  source:
    path: kubernetes/gitops/front-app
    repoURL: https://github.com/dannymartinm/container-expert-scratch.git
    targetRevision: HEAD
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
  #   syncOptions:
  #   - Validate=false
